### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tehhowch**
+ Some punctuation changes (me)
+ major improvements (tsitu)

### CODE REVIEW

**Comment by tsitu** [comment]
@DevJackSmith 

Let me know if I've misstated something in the rewritten portions.

**Comment by tehhowch** [comment]
GitHub must not diff the badge images well:
image


 If you view the readme on the branch, they load just fine:

image

**Comment by tsitu** [comment]
Is this via rich diff? If so, there seems to be a bug whereby it tries to resolve the relative URL using the "master" aka `chrome-ff-opera` branch when you switch over from source diff:

richdiff1

However, once you're on the rich diff, a page refresh makes the relative URL resolve properly:

richdiff2

**Comment by tehhowch** [comment]
Good to know. I'd review and approve this, but I can't approve my own PR 😁 

🚀

**Pull request merged**
