### PR TITLE
Added Queso Geyser stage separation

### PR DESCRIPTION
**Pull request by tsitu**
Stages:

- Cork Collecting
- Pressure Building
- Tiny Eruption
- Small Eruption
- Medium Eruption
- Large Eruption
- Epic Eruption

### CODE REVIEW

**Comment by tsitu** [comment]
The stage names are a simple truncation of the mouse group names, which are `Cork Collector` and `Pressure Builder`. I'll ask around on Discord to get an idea for what users would prefer - `Cork / Pressure` or `Collecting / Corked` or even `Uncorked / Corked`. Regardless, if a stage name turns out to be unpopular later on it can always be adjusted.

---

Re: nest claim logic, I think it would be best to handle that in a separate `recordNestLoot` function, similar to `recordConvertible`, except have it check for a request to `managers/ajax/environment/queso_geyser.php` instead.

Here's a sample JSON response from a Small Eruption in which I armed Mild Queso all the way.

```json
"queso_geyser_nest_loot": {
    "mice": [
      {
        "name": "Sizzle Pup",
        "display_order": 21,
        "large": "https://www.mousehuntgame.com/images/mice/large/b104d385f0830d2c2fd98fb28cf027b9.jpg?cv=240",
        "mouse_id": 978,
        "items": [
          {
            "type": "rubber_crafting_item",
            "quantity": 17,
            "is_jackpot": null,
            "is_wildtonic": null
          },
          {
            "type": "amber_queso_stat_item",
            "quantity": 3,
            "is_jackpot": null,
            "is_wildtonic": null
          }
        ],
        "wild_tonic_items": [],
        "type": "geyser_eruption_dragon_small",
        "has_jackpot": true,
        "merged_items": [
          {
            "type": "rubber_crafting_item",
            "quantity": 17,
            "is_jackpot": null,
            "is_wildtonic": null,
            "name": "Congealed Rubber",
            "thumb": "https://www.mousehuntgame.com/images/items/crafting_items/thumbnails/88fb12e07d6d63e738241bc9a531700b.gif?cv=240",
            "quantity_formatted": 17,
            "quantity_abbreviated": 17
          },
          {
            "type": "amber_queso_stat_item",
            "quantity": 3,
            "is_jackpot": null,
            "is_wildtonic": null,
            "name": "Solidified Amber Queso",
            "thumb": "https://www.mousehuntgame.com/images/items/stats/a8397e0218a4762602a429f4f4826690.gif?cv=240",
            "quantity_formatted": 3,
            "quantity_abbreviated": 3
          }
        ],
        "caught": 3,
        "num_items": 2,
        "num_wild_tonic_items": 0,
        "num_all_items": 2,
        "css_class": "half"
      },
      {
        "name": "Mild Spicekin",
        "display_order": 20,
        "large": "https://www.mousehuntgame.com/images/mice/large/de5d82dfb71d83d599ad48f9e33ceab0.jpg?cv=240",
        "mouse_id": 977,
        "items": [
          {
            "type": "medium_spice_crafting_item",
            "quantity": 20,
            "is_jackpot": null,
            "is_wildtonic": null
          },
          {
            "type": "bland_queso_cheese",
            "quantity": 40,
            "is_jackpot": null,
            "is_wildtonic": null
          }
        ],
        "wild_tonic_items": [],
        "type": "geyser_eruption_dragon_mild",
        "has_jackpot": true,
        "merged_items": [
          {
            "type": "medium_spice_crafting_item",
            "quantity": 20,
            "is_jackpot": null,
            "is_wildtonic": null,
            "name": "Medium Spice Leaf",
            "thumb": "https://www.mousehuntgame.com/images/items/crafting_items/thumbnails/c697a753288aa6f8b0c343a9cc4bfddb.gif?cv=240",
            "quantity_formatted": 20,
            "quantity_abbreviated": 20
          },
          {
            "type": "bland_queso_cheese",
            "quantity": 40,
            "is_jackpot": null,
            "is_wildtonic": null,
            "name": "Bland Queso",
            "thumb": "https://www.mousehuntgame.com/images/items/bait/4752dbfdce202c0d7ad60ce0bacbebae.gif?cv=240",
            "quantity_formatted": 40,
            "quantity_abbreviated": 40
          }
        ],
        "caught": 5,
        "num_items": 2,
        "num_wild_tonic_items": 0,
        "num_all_items": 2,
        "css_class": "half"
      }
    ],
    "dusted": [],
    "has_dusted": null,
    "jackpot_items": [
      "hydro_geyser_trap_stat_item",
      "tactical_geyser_trap_stat_item",
      "physical_geyser_trap_stat_item",
      "draconic_geyser_trap_crafting_item",
      "ultimate_trinket"
    ],
    "dusted_loot_preview": [
      {
        "name": "Congealed Rubber",
        "thumb": "https://www.mousehuntgame.com/images/items/crafting_items/thumbnails/88fb12e07d6d63e738241bc9a531700b.gif?cv=240",
        "type": "rubber_crafting_item",
        "slot": "cork_mat"
      },
      {
        "name": "Solidified Amber Queso",
        "thumb": "https://www.mousehuntgame.com/images/items/stats/a8397e0218a4762602a429f4f4826690.gif?cv=240",
        "type": "amber_queso_stat_item",
        "slot": "amber"
      },
      {
        "name": "Bland Queso",
        "thumb": "https://www.mousehuntgame.com/images/items/bait/4752dbfdce202c0d7ad60ce0bacbebae.gif?cv=240",
        "type": "bland_queso_cheese",
        "slot": "bland"
      },
      {
        "name": "Medium Spice Leaf",
        "thumb": "https://www.mousehuntgame.com/images/items/crafting_items/thumbnails/c697a753288aa6f8b0c343a9cc4bfddb.gif?cv=240",
        "type": "medium_spice_crafting_item",
        "slot": "spice"
      }
    ],
    "share_journal_id": 19426
  }
```

**Comment by tsitu** [comment]
Having trouble pushing again to this branch... PM'd Jack on Discord the error I've been getting:

```
remote: error: GH006: Protected branch update failed for refs/heads/queso-geyser-stages.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/DevJackSmith/mh-helper-extension.git
 ! [remote rejected] queso-geyser-stages -> queso-geyser-stages (protected branch hook declined)
error: failed to push some refs to 'https://github.com/DevJackSmith/mh-helper-extension.git'
```

**Comment by tehhowch** [comment]
Yeah that can happen when all branches are protected instead of just a handful. Solution is to open the branch on your fork and not the remote you're merging to.

**Comment by DevJackSmith** [comment]
fixed to protect only 3 branches (master, chrome-ff-opera and ms-edge)

**Pull request closed without merging**
